### ISSUE TITLE
How can we change the display of column items?

### ISSUE THREAD

**Issue by jlubeck** [sslotsky/violet-paginator#14]
Hey! Sorry to bother you again. Hope you don't mind!

How can I change what gets displayed on a specific column?

2 specific examples.
1) On column B, I'd like to make a link based on information of column A.
2) On column C, I'd like to format what the server is returning to show it like currency.

I'm not asking how to make links or display like currency of course, but how to modify what is about to be shown to whatever else I'd need to.

Hope my question was clear!

Thanks!

**Comment by sslotsky** [comment]
[Check the README](https://github.com/sslotsky/violet-paginator#customizing-violetdatatable)

**Comment by jlubeck** [comment]
Ohhhh, now I got it!! When I initially read the Readme I thought it was just for changing the headers, pfff. dumb me. I have it working now, and it's very powerful! Thanks once again!! I love your library! :D
