### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by markau** [sslotsky/violet-paginator#25]
Sam, this library just keeps getting better. So slick.

I have some suggestions that I don't believe are covered in the documents anywhere:

* A placeholder component to display if no records are returned from the API (i.e. "no records found" instead of a table header with no table contents)
* Ability to set one of the other font awesome icons as the spinner (I'm partial to `fa-circle-o-notch` and `fa-refresh`)
* In the [DataTable](https://sslotsky.gitbooks.io/violet-paginator/content/violetdatatable.html) it would be nice to be able to replace the Active column header with a "Select all" checkbox (but ideally custom switcher component).

**Comment by sslotsky** [comment]
Hi @markau, I'm glad you're still enjoying the library. I do appreciate your suggestions, and they're not entirely unreasonable, but at the same time, I can't expect to be able to support every possible UI request. That's why I made it easy to write your own pagination components.

To demonstrate how easy that is, here's one that I wrote just today for a blogging site that I'm hacking on (using `violet-paginator@2.x`):

```javascript
import React from 'react'
import { decorators } from 'violet-paginator'

import { Snippet, Markdown } from 'POSTS/Show'
import { Video } from 'POSTS/components/Preview/blockTypes'

function SnippetPreview(props) {
  const options = {
    readOnly: true
  }

  return (
    <Snippet
      options={options}
      {...props}
    />
  )
}

const components = {
  snippet: SnippetPreview,
  markdown: Markdown,
  video: Video
}

export function renderPost(post, i) {
  const block = post.get('blocks').first().toJS();
  const Block = components[block.format]

  return (
    <div key={i}>
      <h2>{post.get('title')}</h2>
      <div className="list-preview">
        <Block {...block} />
      </div>
    </div>
  )
}

export function Browse({ results }) {
  return (
    <div className="soft-half">
      {results.map(renderPost)}
    </div>
  )
}

const Decorated = decorators.tabulate(Browse)

export default () => (
  <Decorated listId="posts" />
)
```

**Comment by markau** [comment]
No worries, they are just thoughts I've had that you may or may not want to consider as you develop the library. I'll investigate the posted example in some more depth. Cheers.
