### ISSUE TITLE
simpleComposable UPDATE_ITEM action not firing

### ISSUE THREAD

**Issue by markau** [sslotsky/violet-paginator#4]
I am including a toggle in the data grid, and following the doco on [simpleComposable](https://sslotsky.gitbooks.io/violet-paginator/content/composing_actions.html).

The redux flow is working - i.e. the function is called via props and passes through the `recipe` item. The `recipes.get('id')` and `recipes.get('active')` properties are present and set as expected.

The problem is that the `pageActions.updateItem` function is not doing anything. If I monitor the state with Redux DevTools, I do not see any actions being dispatched by this function. The source suggests the `UPDATE_ITEM` action should be dispatched.

**Comment by sslotsky** [comment]
`simpleComposables` are actions so simply calling them isn't enough. They need to be dispatched. This can be done by injecting the function into your component with the `mapDispatchToProps` arg.

From the [composing actions docs](https://sslotsky.gitbooks.io/violet-paginator/content/composing_actions.html):

```javascript
export default connect(
  () => ({}),
  { fetch: fetchRecipes, toggle: toggleActive }
)(Recipes)
```

**Comment by markau** [comment]
Ahhhh OK. I see. Thank you!
