### ISSUE TITLE
setFilters with array values merges values - would prefer it replace values

### ISSUE THREAD

**Issue by drewjohnson10** [sslotsky/violet-paginator#5]
When I call `setFilters` with an array of (new) values, the new values are merged with the old values.  Old/obsolete values are never removed.  

For example, if I set a filter `foo: [1, 2]`, then call setFilter with `foo: [1]`, I see a network call with the parameters `foo[]=1&foo[]=1`.  

Then, if I set `foo: [3]`, the network call is `foo[]=3&foo[]=1`.  Preferred behavior would be a network call with `foo[]=3`.

I think this can be resolved by using `mergeDeepWith` (https://facebook.github.io/immutable-js/docs/#/Map/mergeDeepWith) instead of `mergeDeep` within [setFilters](https://github.com/sslotsky/violet-paginator/blob/master/src/reducer.js#L135])

**Comment by sslotsky** [comment]
@drewjohnson10 submitted #6 to address this issue. I think the unit test proves that it solves your problem, but before I merge, do you want to try it locally by pulling down the branch and using `npm link`?

**Comment by sslotsky** [comment]
Published in 1.8.4
